### ISSUE TITLE
Solid Code of Conduct

### ISSUE THREAD

**Issue by csarven** [solid-contrib/getting-started#1]
FYI, if this repository does not use the [Solid Code of Conduct](https://github.com/solid/process/blob/main/code-of-conduct.md), it'll be out of the purview of the Solid Project (and Solid Team). So, consider using the Solid CoC instead or clarify whether this repository sets additional or different acceptable behaviours.

**Comment by YetAnotherJonWilson** [comment]
Hi @csarven,

Thank you for opening the issue, I do want to make sure we take the CoC seriously, and use the right version.

I used the same Code of Conduct (the Contributor Covenant) that I found being used by Solid, here: https://github.com/solid/process/blob/main/code-of-conduct.md, and adapted it for use in this repo, by adding my name and email to the enforcement section. I think the only other difference at the moment is in the top section--where the Solid CoC links to this, [Positive Work Environment at W3C: Code of Ethics and Professional Conduct](https://www.w3.org/Consortium/cepc/). I did not include that link only because I hadn't read through all of it and didn't want to adopt it without reading and understanding it thoroughly.

But, should I change those two things, or anything else? 

Thanks very much!

**Comment by timea-solid** [comment]
@csarven I believe what Jon did is enough. Any further suggestions on your side?

**Comment by YetAnotherJonWilson** [comment]
@csarven @timea-solid 

Can we close this?

**Comment by csarven** [comment]
@YetAnotherJonWilson , your patience and checking in is appreciated!

In response to https://github.com/solid/team/issues/36 , the recommendation from https://github.com/solid/team/blob/main/meetings/2023-06-14.md#role-of-solid-contrib is that this repository should re-use https://github.com/solid/process/blob/main/code-of-conduct.md but with its own CoC committee - in essence, it is pretty close to what's currently being done but needs an update.

See example: https://github.com/CommunitySolidServer/CommunitySolidServer/blob/main/CODE_OF_CONDUCT.md (background:  https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1668 ). So, consider simply copying the content short blurb referencing the Solid CoC, and then use names of individuals that'd be responsible for enforcement.

This issue can be resolved with a PR capturing the above.

**Comment by YetAnotherJonWilson** [comment]
Thanks @csarven, here it is: https://github.com/solid-contrib/getting-started/pull/21

Before we merge it and close the issue, @timea-solid, would you like for me to add your name/email as a member of the Committee for resolving issues in this repo?
